services:
  - type: web
    name: minecraft-telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false  # Мы введем его вручную